//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio_OrnelasSamuel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dato
    {
        public string Id { get; set; }
        public Nullable<int> Clientes { get; set; }
        public string Texto { get; set; }
        public string UsuarioId { get; set; }
        public string Descripcion_Hecho { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
