//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio_OrnelasSamuel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public string Id { get; set; }
        public string UsuarioID { get; set; }
        public string Descripcion { get; set; }
        public string Servicio1 { get; set; }
        public string Descripcion_Servicio { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
